services:
  camel-spotify:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
