spring.application.name=camel-spotify
# Railway inyecta la variable PORT automáticamente
server.port=${PORT:8080}

# Spotify credentials (overridden by env vars in Docker)
spotify.client-id=${SPOTIFY_CLIENT_ID:ab62ef265c124679ba176f26a35e47a9}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET:2840201292c5450aa7dfe2ee067f78f7}
spotify.token-url=https://accounts.spotify.com/api/token
spotify.api-url=https://api.spotify.com/v1

# JWT
jwt.secret=${JWT_SECRET:mySuperSecretKeyForJWTThatMustBe32CharsMin!!}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Credenciales B2B (clientes que consumen esta API)
auth.client-id=${AUTH_CLIENT_ID:camel-client}
auth.client-secret=${AUTH_CLIENT_SECRET:camel-secret-2024}
