spring.application.name=camel-spotify
server.port=8080

# Spotify credentials (overridden by env vars in Docker)
spotify.client-id=${SPOTIFY_CLIENT_ID:ab62ef265c124679ba176f26a35e47a9}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET:2840201292c5450aa7dfe2ee067f78f7}
spotify.token-url=https://accounts.spotify.com/api/token
spotify.api-url=https://api.spotify.com/v1
